application: jkirchartz
version: 1
runtime: python27
# Apparently this is required to use python27
threadsafe: false
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /
  static_files: index.html
  upload: index\.html
- url: /robots.txt
  static_files: robots.txt
  upload: robots\.txt
- url: /untiny
  script: untiny.app
- url: /megafeed
  script: megafeed.app
- url: /_ah/.*
  script: chatbot.app
  
inbound_services:
- xmpp_message
