application: jkirchartz
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /
  static_files: index.html
  upload: index\.html
- url: /(.*\.(html))
  static_files: static/\1
  upload: static/(.*\.(html))
- url: /robots.txt
  static_files: robots.txt
  upload: robots\.txt
- url: /untiny
  script: untiny.app
- url: /megafeed
  script: megafeed.app
- url: /jobfeed
  script: jobfeed.app
- url: /jobportal.json
  script: jobportal.app
- url: /researchfeed
  script: researchfeed.app
- url: /_ah/.*
  script: chatbot.app

inbound_services:
- xmpp_message

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: lxml
  version: latest
